language: php
php:
    - "5.4"
    - "5.3"


language: node_js
node_js:
  - "0.8"
before_install: cd subtrees/bootstrap/
before_install: npm install -g grunt-cli
install: cd subtrees/bootstrap/
install: npm install
before_script: cd subtrees/bootstrap/
before_script: grunt dist